### ISSUE TITLE
Study obstacles towards making mlkem-native C90 compliant

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#459]
Acceptance criteria:
- [ ] A list of issues/idioms that need to be addressed to make mlkem-native C90 compliant.

If it turns out to be simple, just open a PR and fix it.

**Comment by mkannwischer** [comment]
I gave this a try. I worked on a PoC for x86_64 [here](https://github.com/pq-code-package/mlkem-native/tree/c90) - this does build with `-std=c90` without warnings, but not everything is implemented the way we would want it yet. 

Here are the obstacles I found:
- `C++ style comments are not allowed in ISO C90`: We would have to replace all `//` comments with `/* */` comments. Pain: medium.  (Easy to do in general, but a bit off work if we want it clean. To test, I removed all `//` comments in 0c1f4450dcc90c120a3c0522a6295df6f30272f7) 
- `‘for’ loop initial declarations are only allowed in C99 or C11 mode`: We have to pull out all variable declarations out of the loop. Pain: low  (implemented by be247bd4255c287d4eb1befe334e3528e0020513)
- ` use of C99 long long integer constant` (e.g., 0x0000000000000001ULL). OpenSSL works around this by setting `-Wno-long-long` (done in b4bf0872e13a3e6d5d8a54817295f11732cb427a) 
- ` anonymous variadic macros were introduced in C99` - the macros in `debug.h` would have to defined differently when compiling without debug flags. Pain: low 
(Changed in cabcd7957ad6c970e3a92297fdcc28383c9e84b7)
- `ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]`. We'll have to move all declaration to the top. Pain: low. 
(This sounds painful, but requires surprisingly few changed - see 7a881c3915e6e5d69e9ae3a84f67ad5da9c163be)
- No `restrict` - we rarely use this anyway, but maybe we want to in the future. We can define it separately, so that modern compiler can still apply the optimizations. Pain: low (Done in 631a4024ec8017855abd501b3fcf791a7efad96b)
- No `inline` - this is a bigger painpoint because if we do remove the inline on C90 builds, the compiler complains about a lot of unused functions in headers (as not all CUs are using them). We will have to silence those using `__attribute__((unused))` which is what OpenSSL is doing too. Pain: low (66a998a106b0b1e47e2262c9ab90a92fcc7976ba) 
- Minor change for initializing pointer arrays done in 1783b7d60fc1102445987abaf20458b4428c8a61. 


Overall: I don't want to switch to C90 for our own builds, but achieving C90 compliance requires moderate changes of which I find the comments the most annoying, but I can live with that. 

What do you think @hanno-becker @rod-chapman? I can open a PR that changes everything nicely over the weekend.

**Comment by rod-chapman** [comment]
What is the requirement to do this? Are there potential customers/users who demand C90 compliance?
