### ISSUE TITLE
Document clang-format version requirements

### ISSUE THREAD

**Issue by dkostic** [pq-code-package/mlkem-native#581]
**Describe the bug**
Script `autogenerate_files.py` fails on two of my machines.
First setup is c7i EC2 instance with Intel(R) Xeon(R) Platinum 8488C and:
```
➜  ~ uname -a
22~22.04.1-Ubuntu SMP Thu Nov 21 22:13:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

➜  cc --version
cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  clang --version
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

➜  clang-format --version
Ubuntu clang-format version 14.0.0-1ubuntu1.1
```

Second setup is M1 based macbook with:
```
➜  ~ clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

➜  clang-format --version
clang-format version 16.0.6
```

**Platform**: see above

**Compiler**: see above

**How to reproduce**
```
➜  temp git clone https://github.com/pq-code-package/mlkem-native.git
Cloning into 'mlkem-native'...
remote: Enumerating objects: 21510, done.
remote: Counting objects: 100% (348/348), done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 21510 (delta 254), reused 184 (delta 173), pack-reused 21162 (from 3)
Receiving objects: 100% (21510/21510), 7.42 MiB | 32.34 MiB/s, done.
Resolving deltas: 100% (10253/10253), done.
➜  temp cd mlkem-native
➜  mlkem-native git:(main) python3 scripts/autogenerate_files.py
Failed to auto-format autogenerated code (clang-format return code 1
```

**Expected behavior**

**Additional context**

**Comment by hanno-becker** [comment]
This is probably a version issue. We pin clang-tools to v17 in nix and never test the autogeneration script / clang-format outside of the nix environment. @potsrevennil can you investigate?

**Comment by hanno-becker** [comment]
The `Macros` option which we use to avoid clang-format messing up the CBMC annotations, was introduced in v17 only.

**Comment by hanno-becker** [comment]
My preference:
1. Check clang-format version in `format` script. Fail if it's <17. One can ignore unknown options with --Wno-error=unknown, but that's not really useful because it will then fail in CI. A good error message and reference to nix is the best we can do I think.
2. In `autogenerate_files.py`, emit unformatted code if clang-format fails, but issue a warning that the code still needs to be formatted.

Even better would be to not use v17 options, but I have already spent hours trying to make clang-format work with CBMC annotations and am out of ideas beyond what we currently do.

**Comment by hanno-becker** [comment]
Different approach taken in #586: nudge the developer to setup nix which bundles a working toolset, rather than attempting to state the minimum version requirements.

**Comment by mkannwischer** [comment]
Right now we assume developers to be using dev dependencies (e.g., clang-format) installed via nix in which case there should not be a problem.

Just making older versions of `clang-format` work would merely be useful for the autogeneration script, not for the more involved `format` script.
I prefer making our nix configuration more robust on more platforms and improve documentation rather than supporting development without nix.
